spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ground_standard?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    initialization-mode: always
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.taobao.groundstandard.entities